### ISSUE TITLE
Split times aren't written to file

### ISSUE THREAD

**Issue by luciferofastora** [paoloose/urn#15]
When I start a new run, the attempt_count increments, showing that urn does have write access to the file. 
When I split a section, the "Previous Segment" time does not appear, nor does the file update.
When I finish a run (split after the last segment), the timer stops, shows a Sum of best segments and Personal best with the current time, but does not update the file to reflect these times. 
Restarting the timer will again increment the attempt_count, while cancelling it will correctly decrement the counter. 

So apparently the app can write to the file, it just doesn't write the times.
Launching it from the command line doesn't yield any output. 

I just pulled and installed the latest version, made sure all the dependencies were up to date etc. Searching both past issues here and on the upstream project has brought up no similar issues. Any further steps I could take to debug this?

**Comment by luciferofastora** [comment]
[Demo.json](https://github.com/paoloose/urn/files/13759376/Demo.json)
The demo split file used. Note the incremented `attempt_count` despite all times being empty.

**Comment by paoloose** [comment]
Thanks for reporting. I'll definitely review this when I have time, probably writes are not being flushed properly.

**Comment by paoloose** [comment]
Hey, I completely forgot about this, but you need to hit save or save bests if you want to save your times for the current run

![image](https://github.com/paoloose/urn/assets/98111143/c5ada706-4c4c-4d41-aa33-f26ceb418e4c)

**Comment by paoloose** [comment]
This feature exists because you don't necessarily want to consider the current run to be your new best because you may be just testing out or skipping some splits or skip them by accident. I'll submit a documentation update to clarify this behavior.

**Comment by paoloose** [comment]
About the previous segment, can you please clarify what's the problem? :-)

**Comment by luciferofastora** [comment]
Sorry for the delayed response, my PC broke down and I couldn't actually try it until I got it fixed. The explicit saving absolutely makes sense, I just missed that File menu entirely. With that, it now saves correctly and the issue is closed as far as I'm concerned.

The "previous segment" is one of the comparisons at the bottom. It should compare the segment I last split against the PB for that segment, which obviously doesn't work if I never saved that PB.

**Comment by paoloose** [comment]
Nice!
