### ISSUE TITLE
Not on top when in full screen

### ISSUE THREAD

**Issue by pizzuhh** [paoloose/urn#21]
When I'm in fullscreen (pressed f4 in undertale or in full screen in youtube) the window goes below. I think it's probably dwm issue. Is there a way to fix this?

**Comment by paoloose** [comment]
I'm afraid that's the expected behavior. The 'keep always on top' window hint is not intended to work in fullscreen. If you want to achieve this you'll need to rely on your compositor/wm features. Please let me know if you find a way :)
