### ISSUE TITLE
Black sreen

### ISSUE THREAD

**Issue by PierrePharel** [paoloose/urn#3]
When I start the app and I load a split file (json), I got a full black screen

**Comment by paoloose** [comment]
Sorry for the delay.

That may be due a malformed json file, have you tried using the example in `splits/sotn.json`? If I'm too late, I think that providing more and better examples in the `splits` directory may prevent this in the future

**Comment by paoloose** [comment]
Update: no more black screens, now helpful messages will be provided when urn fails to parse a json file

![image](https://user-images.githubusercontent.com/98111143/226089268-ce0eb268-a64b-4c86-a01a-aa52288ad4f2.png)
