### ISSUE TITLE
Timer font should be monospace to avoid time jittering around.

### ISSUE THREAD

**Issue by Shadetheartist** [paoloose/urn#4]
When the time font is not monospaced the differences in character widths cause the time text to jitter around, using monospace or possibly aligning the text left or center would also fix this issue.

**Comment by paoloose** [comment]
Sadly the [available CSS properties](https://docs.gtk.org/gtk3/css-properties.html) for gtk3 don't support alignment, making it impossible to customize this using a theme, AFAIK. You can make that a separate issue to see if someone can help with this, if you want to.

Currently, the `font-family` for the `.timer` class is not defined on `urn-gtk.css`, so the system default font will be used. In most cases, it should fallback to `DejaVu Sans`, which works great, and shouldn't cause jittering for numbers. Have you experienced any issues with this font, or are you referring to the idea of supporting non-monospace font types?

**Comment by Shadetheartist** [comment]
Oh that's weird, i had no problem modifying the css file to use a monospace. I jjust added `font-family: monospace;` to `.timer`  With the default font it was not monospace and i was experiencing jitter.

![image](https://user-images.githubusercontent.com/8973930/226074124-d238295f-cb3c-4b6d-8d61-5d71da2d64fb.png)

**Comment by paoloose** [comment]
> Oh that's weird, i had no problem modifying the css file to use a monospace

Yeah, I was referring to the fact that horizontal alignment (left-center-right), is not supported on CSS for gtk3, that sucks

> With the default font it was not monospace and i was experiencing jitter.

Thanks for pointing this out. It's not convenient to rely on the default system font, a `font-family` should be defined, at least for the timer that is vulnerable to jittering. Was `DejaVu Sans` the default font that you mention?

**Comment by Shadetheartist** [comment]
I'm using gnome and my default fonts are:
![image](https://user-images.githubusercontent.com/8973930/226075586-082bc711-0742-4672-ada2-42690fc5e2e1.png)

**Comment by paoloose** [comment]
Thanks! So I set `DejaVu Sans` as default font for the timer, it works great. Also I document it as an optional dependency. I thinks that solves this issue for now.
