### ISSUE TITLE
urn segfaults when closed through the window manager

### ISSUE THREAD

**Issue by fgaz** [paoloose/urn#6]
urn segfaults when closed through the window manager (eg. "X" on the title bar or ALT+F4), but closes cleanly with File->Quit or ctrl+C

**Comment by paoloose** [comment]
What OS and desktop environment are you using? is this issue happening consistently or only in certain states of the application?

I would appreciate it if you could debug this further since I wasn't able to reproduce it on my machine (i3wn + debian 12). i3 does not have close buttons but the destroy signal should be handled in the same way

**Comment by fgaz** [comment]
Ah, sorry, I assumed it would be easily reproducible. I'm on NixOS linux, Awesome WM. The issue always happens when closing through the window manager.

And here's a backtrace:

```
#0  0x00007fda96512003 in g_type_check_instance_cast ()
   from /nix/store/4x515ma88q96phhjyr8y56im6y5lgz83-glib-2.74.5/lib/libgobject-2.0.so.0
#1  0x0000000000404cb8 in urn_app_window_step (data=0x626ce0) at urn-gtk.c:128
#2  0x00007fda963f3ffa in g_timeout_dispatch () from /nix/store/4x515ma88q96phhjyr8y56im6y5lgz83-glib-2.74.5/lib/libglib-2.0.so.0
#3  0x00007fda963f34df in g_main_context_dispatch () from /nix/store/4x515ma88q96phhjyr8y56im6y5lgz83-glib-2.74.5/lib/libglib-2.0.so.0
#4  0x00007fda963f3898 in g_main_context_iterate.constprop ()
   from /nix/store/4x515ma88q96phhjyr8y56im6y5lgz83-glib-2.74.5/lib/libglib-2.0.so.0
#5  0x00007fda963f392c in g_main_context_iteration () from /nix/store/4x515ma88q96phhjyr8y56im6y5lgz83-glib-2.74.5/lib/libglib-2.0.so.0
#6  0x00007fda9661bff8 in g_application_run () from /nix/store/4x515ma88q96phhjyr8y56im6y5lgz83-glib-2.74.5/lib/libgio-2.0.so.0
#7  0x00007fda9606224e in __libc_start_call_main () from /nix/store/8bmp6r3a0xfha3wj36phlc47clh9w81l-glibc-2.35-224/lib/libc.so.6
#8  0x00007fda96062309 in __libc_start_main_impl () from /nix/store/8bmp6r3a0xfha3wj36phlc47clh9w81l-glibc-2.35-224/lib/libc.so.6
#9  0x0000000000404b35 in _start ()
```

**Comment by fgaz** [comment]
Considering that you can't reproduce this on debian and that I can reproduce the same error with some other gtk programs, I think this issue is due to NixOS, so I'm closing

**Comment by paoloose** [comment]
That's interesting, unfortunately I couldn't find any related issues, which is weird. If it's possible to handle this from urn, I will reopen this
