### ISSUE TITLE
how would you install this on arch?

### ISSUE THREAD

**Issue by loglot** [paoloose/urn#8]

**Comment by paoloose** [comment]
It seems like there were previous efforts to distribute an urn package for the AUR. See <https://aur.archlinux.org/packages/urn-git>.

Gladly to know about this, please tell me if it works for you so I can add it to the README with some other repository packages that I found for other distros.

**Comment by logloglol** [comment]
i'm not great with the AUR website, so i have no idea how to install anything from it, i'm very new to arch

**Comment by logloglol** [comment]
so, i'm on a steamdeck which... removes some important things, so i get this error while i was building it

`==> ERROR: A failure occurred in build().
    Aborting...
`
i don't know how to fix it

**Comment by paoloose** [comment]
Can you have the complete build log so I can see the error details?

Probably [missing AUR prerequisites](https://wiki.archlinux.org/title/Arch_User_Repository#Prerequisites) that you need to start building packages, they are bundled in the [`base-devel`](https://archlinux.org/packages/core/any/base-devel/) meta package.

**Comment by logloglol** [comment]
after getting the prerequisites, here is the full log in the terminal

```(1)(deck@steamdeck urn-git)$ makepkg
==> Making package: urn-git r134.8efdabc-1 (Thu 27 Jul 2023 01:01:27 AM CDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating urn git repo...
  -> Updating urn-themes git repo...
  -> Found urn.desktop
==> Validating source files with sha1sums...
    urn ... Skipped
    urn-themes ... Skipped
    urn.desktop ... Passed
==> Extracting sources...
  -> Creating working copy of urn git repo...
Switched to a new branch 'makepkg'
  -> Creating working copy of urn-themes git repo...
Switched to a new branch 'makepkg'
==> Starting prepare()...
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection `pkg-config --cflags gtk+-3.0 x11 jansson` -Wall -Wno-unused-parameter -std=gnu99 -I/usr/include/gtk-3.0/   -c -o urn-gtk.o urn-gtk.c
urn-gtk.c:1:10: fatal error: string.h: No such file or directory
    1 | #include <string.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [<builtin>: urn-gtk.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
(4)(deck@steamdeck urn-git)$ 
```

**Comment by paoloose** [comment]
> urn-gtk.c:1:10: fatal error: string.h: No such file or directory
>    1 | #include <string.h>
>      |          ^~~~~~~~~~

It seems like your system can't found standard C libraries like <string.h>. I found [this post from r/steamdeck](https://www.reddit.com/r/SteamDeck/comments/t92ozw/for_compiling_c_code/), there are some missing header files that you need to install manually:

> Now, valve deleted some random files from packages so rootfs can fit in 5 gb, which really confused me. You already have glibc and linux-api-headers installed, but they have missing files.
>
> So fix them: pacman -S glibc linux-api-headers

The above command should fix it, I guess.

**Comment by logloglol** [comment]
none of this worked, i swiched to a different distro on an sd card and i got it to work. however, i have no idea how to open it, urn.desktop doesn't work, what should i do

**Comment by paoloose** [comment]
Oh, all system applications need a `.desktop` file located in one of your `$XDG_DATA_DIRS` directories (mostly located in `/usr/local/share/applications` and `/usr/share/applications`).

You are not intended to use the `.desktop` files directly, they should be indexed by your applications launcher, for example, I'm using [rofi](https://github.com/davatorium/rofi) as my application launcher and all my desktop applications that have a `.desktop` files in the said directories are listed there, here you can see Urn being listed too:

![ss_15](https://github.com/paoloose/urn/assets/98111143/ab04f86e-ccf4-4d0e-bf88-d18c2ced267c)

So it depends how you start your applications, your distro should have a way to launch desktop applications installed on your system.

Since desktop files are just plain text you can inspect the content of `urn.desktop`:

```desktop
[Desktop Entry]
Name=Urn
Exec=/usr/local/bin/urn-gtk
Icon=urn
Type=Application
Categories=GTK;GNOME;Utility;
```

The `Exec` field is where the application binary is located, so running `/usr/local/bin/urn-gtk` will also start Urn (and it most likely you can directly type `urn-gtk` in your console and will work as well).

**Comment by logloglol** [comment]
so this is what my `/usr/local/bin` folder looks like
![image](https://github.com/paoloose/urn/assets/88983354/bf9cca9e-8b4d-4cec-a2c9-46333aeb8b7d)

**Comment by paoloose** [comment]
The example I showed was the .desktop file that is distributed in this repository. It seems that the AUR uses `/usr/bin/urn-gtk` instead.

**Comment by loglot** [comment]
in that folder there is a lot of stuff, just not urn. however, i was able to find this path `/home/deck/urn-git/pkg/urn-git/usr/bin/` it DOES have `urn-gtk`, this file was also found in this folder `/home/deck/urn-git/src/urn/`, the `urn.desktop` file is also in the second path

**Comment by paoloose** [comment]
Nice!

> in that folder there is a lot of stuff, just not urn

Yeah, `/usr/bin` is where the majority of system binary files are located. Its likely that its already in your PATH so you can just type `urn-gtk` in your console to start the program.

So, its working fine?

**Comment by loglot** [comment]
i'm a bit confused, how did my message signify that it was working?

**Comment by loglot** [comment]
also, it would be nicer if we had a quicker way to communicate

**Comment by paoloose** [comment]
> i'm a bit confused, how did my message signify that it was working?

Didn't assume that, I was just asking since you didn't provide further details after finding the binary. Anyways yeah, would be nicer if you reach me out as `paoloose` on Discord.

**Comment by loglot** [comment]
```git clone https://aur.archlinux.org/urn-git.git
cd urn-git
makepkg
sudo pacman -U urn-git-r134.8efdabc-1-x86_64.pkg.tar.zst
```

**Comment by loglot** [comment]
```
git clone https://aur.archlinux.org/urn-git.git
cd urn-git
makepkg
sudo pacman -U urn-git-r134.8efdabc-1-x86_64.pkg.tar.zst
```
